[project]
name = "rendezqueue"
version = "0.0.0"
description = "Client and server for a rendezqueue service that just swaps values."
license = { text = "0BSD" }

authors = [
  { name = "Alex Klinkhamer", email = "about.rendezqueue@grencez.dev" }
]
dependencies = [
]
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/rendezqueue/rendezqueue-py"
Repository = "https://github.com/rendezqueue/rendezqueue-py"
Issues = "https://github.com/rendezqueue/rendezqueue-py/issues"

[project.scripts]
rendezqueue-client = "rendezqueue.cli:main"
rendezqueue-server = "rendezqueue.server:run"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
  "pytest",
  "ruff==0.15.22",
  "sxpb @ git+https://github.com/sxproto/sxpb-py@75391a98928f345114d539ecab880dc292e0ea9d",
  "ty==0.0.64",
]

[tool.pdm]
package-dir = "src"

[tool.pytest.ini_options]
pythonpath = ["src", "test"]
testpaths = ["test"]

[tool.pdm.scripts]
check-format = "ruff check"
check-type = "ty check"
lint-sxpb = "sxpb-lint --ignore-file .gitignore"
tidy-python = "ruff format"
tidy-sxpb = "sxpb-tidy --ignore-file .gitignore"
tidy = {composite = ["tidy-python", "tidy-sxpb"]}
lint = {composite = ["check-format", "check-type", "lint-sxpb"]}
test = "pytest -q"
tidytest = {composite = ["tidy", "lint", "test"]}

[tool.ty.environment]
root = ["src", "test"]
